steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args:
  - test
- name: maven:3-jdk-8
  entrypoint: mvn
  args:
  - package
  - -Dmaven.test.skip=true
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/clientmanagerapi:$COMMIT_SHA
  - --build-arg=JAR_FILE=target/*.jar
  - .
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/$PROJECT_ID/clientmanagerapi:$COMMIT_SHA
- name: gcr.io/cloud-builders/gke-deploy
  args:
  - run
  - --filename=kub.yaml
  - --image=gcr.io/$PROJECT_ID/clientmanagerapi:$COMMIT_SHA
  - --location=us-central1-c
  - --cluster=tiger-cluster-1
images:
- gcr.io/$PROJECT_ID/clientmanagerapi:$COMMIT_SHA