apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: portal
  name: portal
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: portal
    spec:
      containers:
      - image: gcr.io//clientmanager
        name: clientmanagercontainer
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
